// Code generated by MockGen. DO NOT EDIT.
// Source: webook/internal/service/code.go
//
// Generated by this command:
//
//	mockgen -source=webook/internal/service/code.go -package=svcmocks -destination=webook/internal/service/mocks/code_gen.go
//

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCodeService is a mock of CodeService interface.
type MockCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockCodeServiceMockRecorder
}

// MockCodeServiceMockRecorder is the mock recorder for MockCodeService.
type MockCodeServiceMockRecorder struct {
	mock *MockCodeService
}

// NewMockCodeService creates a new mock instance.
func NewMockCodeService(ctrl *gomock.Controller) *MockCodeService {
	mock := &MockCodeService{ctrl: ctrl}
	mock.recorder = &MockCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeService) EXPECT() *MockCodeServiceMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockCodeService) Send(ctx context.Context, biz, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, biz, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockCodeServiceMockRecorder) Send(ctx, biz, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCodeService)(nil).Send), ctx, biz, phone)
}

// Verify mocks base method.
func (m *MockCodeService) Verify(ctx context.Context, biz, phone, input string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockCodeServiceMockRecorder) Verify(ctx, biz, phone, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCodeService)(nil).Verify), ctx, biz, phone, input)
}

// generateCode mocks base method.
func (m *MockCodeService) generateCode(biz string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "generateCode", biz)
	ret0, _ := ret[0].(string)
	return ret0
}

// generateCode indicates an expected call of generateCode.
func (mr *MockCodeServiceMockRecorder) generateCode(biz any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "generateCode", reflect.TypeOf((*MockCodeService)(nil).generateCode), biz)
}

// getKey mocks base method.
func (m *MockCodeService) getKey(biz, phone string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "getKey", biz, phone)
	ret0, _ := ret[0].(string)
	return ret0
}

// getKey indicates an expected call of getKey.
func (mr *MockCodeServiceMockRecorder) getKey(biz, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "getKey", reflect.TypeOf((*MockCodeService)(nil).getKey), biz, phone)
}
